name: pmsn2023
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.6.0
  sqflite: ^2.3.0
  provider: ^6.0.5
  flutter_slider_drawer: ^2.1.3
  day_night_switcher: ^0.2.0+1
  concentric_transition: ^1.0.3
  path_provider: ^2.1.1
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.13.0
  firebase_core: ^2.23.0
  table_calendar: ^3.0.9
  art_sweetalert: ^0.0.5
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  youtube_player_flutter: ^8.1.2
  flutter_local_notifications: ^16.2.0
  geolocator: ^10.1.0
  animated_floating_buttons: ^0.0.2
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.2
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/.
    - assets/anonymous.png
    - assets/animations/.
    - assets/images/.
